/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Amigos;

import View.Telaprincipal;

/**
 *
 * @author lucas
 */
public class GerenciarAmigos extends javax.swing.JFrame {

    /**
     * Creates new form GerenciarAmigos
     */
    public GerenciarAmigos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_geramg_sair = new javax.swing.JButton();
        bt_geramg_tabelaamigo = new javax.swing.JButton();
        bt_geramg_cadastroamigo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciar amigos");

        bt_geramg_sair.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        bt_geramg_sair.setText("Voltar");
        bt_geramg_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_geramg_sairActionPerformed(evt);
            }
        });

        bt_geramg_tabelaamigo.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        bt_geramg_tabelaamigo.setText("Tabela de amigos");
        bt_geramg_tabelaamigo.setHideActionText(true);
        bt_geramg_tabelaamigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_geramg_tabelaamigoActionPerformed(evt);
            }
        });

        bt_geramg_cadastroamigo.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        bt_geramg_cadastroamigo.setText("Cadastrar amigo");
        bt_geramg_cadastroamigo.setHideActionText(true);
        bt_geramg_cadastroamigo.setMaximumSize(new java.awt.Dimension(148, 23));
        bt_geramg_cadastroamigo.setMinimumSize(new java.awt.Dimension(148, 23));
        bt_geramg_cadastroamigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_geramg_cadastroamigoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Amigos");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_geramg_cadastroamigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_geramg_tabelaamigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(bt_geramg_sair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(bt_geramg_cadastroamigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_geramg_tabelaamigo)
                .addGap(18, 18, 18)
                .addComponent(bt_geramg_sair)
                .addGap(100, 100, 100))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_geramg_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_geramg_sairActionPerformed
        this.setVisible(false);
        Telaprincipal objeto = new Telaprincipal();
        objeto.setVisible(true);
    }//GEN-LAST:event_bt_geramg_sairActionPerformed

    private void bt_geramg_tabelaamigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_geramg_tabelaamigoActionPerformed
        TabelaAmigos objeto = new TabelaAmigos();
        objeto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_geramg_tabelaamigoActionPerformed

    private void bt_geramg_cadastroamigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_geramg_cadastroamigoActionPerformed
        CadastrarAmigos objeto = new CadastrarAmigos();
        objeto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_geramg_cadastroamigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarAmigos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_geramg_cadastroamigo;
    private javax.swing.JButton bt_geramg_sair;
    private javax.swing.JButton bt_geramg_tabelaamigo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
