package View.Amigos;

import Model.Amigo;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TabelaAmigos extends javax.swing.JFrame {

    private Amigo objeto;

    public TabelaAmigos() {
        initComponents();
        this.objeto = new Amigo();
        this.carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_tabelaamg_tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_tabelaamg_nome = new javax.swing.JTextField();
        tf_tabelaamg_tel = new javax.swing.JTextField();
        bt_tabelaamg_editar = new javax.swing.JButton();
        bt_tabelaamg_deletar = new javax.swing.JButton();
        bt_tabelaamg_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabela de amigos");

        tb_tabelaamg_tabela.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        tb_tabelaamg_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_tabelaamg_tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_tabelaamg_tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_tabelaamg_tabela);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel2.setText("Telefone:");

        tf_tabelaamg_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tabelaamg_nomeActionPerformed(evt);
            }
        });

        bt_tabelaamg_editar.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        bt_tabelaamg_editar.setText("Editar");
        bt_tabelaamg_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tabelaamg_editarActionPerformed(evt);
            }
        });

        bt_tabelaamg_deletar.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        bt_tabelaamg_deletar.setText("Deletar");
        bt_tabelaamg_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tabelaamg_deletarActionPerformed(evt);
            }
        });

        bt_tabelaamg_sair.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        bt_tabelaamg_sair.setText("Voltar");
        bt_tabelaamg_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tabelaamg_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_tabelaamg_tel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(bt_tabelaamg_editar)
                        .addGap(86, 86, 86)
                        .addComponent(bt_tabelaamg_deletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(bt_tabelaamg_sair))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_tabelaamg_nome))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_tabelaamg_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_tabelaamg_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_tabelaamg_editar)
                    .addComponent(bt_tabelaamg_deletar)
                    .addComponent(bt_tabelaamg_sair))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_tabelaamg_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tabelaamg_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tabelaamg_nomeActionPerformed

    private void bt_tabelaamg_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tabelaamg_sairActionPerformed
        this.setVisible(false);
        GerenciarAmigos objeto = new GerenciarAmigos();
        objeto.setVisible(true);
    }//GEN-LAST:event_bt_tabelaamg_sairActionPerformed

    private void bt_tabelaamg_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tabelaamg_editarActionPerformed

        try {

            int id = 0;
            String nome = "";
            String nmrtelefone = "";

            if (this.tf_tabelaamg_nome.getText().length() <= 0) {
                throw new Mensagens("O campo 'nome' deve ser preenchido.");
            } else {
                nome = this.tf_tabelaamg_nome.getText();
            }

            if (this.tf_tabelaamg_tel.getText().length() <= 0) {
                throw new Mensagens("O campo 'telefone' deve ser preenchido.");
            } else {
                nmrtelefone = this.tf_tabelaamg_tel.getText();
            }

            if (this.tb_tabelaamg_tabela.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro selecione um amigo para editar.");
            } else {
                id = Integer.parseInt(this.tb_tabelaamg_tabela.getValueAt(this.tb_tabelaamg_tabela.getSelectedRow(), 0).toString());
            }

            if (this.objeto.UpdateAmigoBD(nome, nmrtelefone, id)) {

                this.tf_tabelaamg_nome.setText("");
                this.tf_tabelaamg_tel.setText("");
                JOptionPane.showMessageDialog(rootPane, "Amigo editado com sucesso!");

            }
             System.out.println(this.objeto.getMinhaLista().toString());
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            carregaTabela();
        }
    }//GEN-LAST:event_bt_tabelaamg_editarActionPerformed

    private void tb_tabelaamg_tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_tabelaamg_tabelaMouseClicked

        if (this.tb_tabelaamg_tabela.getSelectedRow() != -1) {

            String nome = this.tb_tabelaamg_tabela.getValueAt(this.tb_tabelaamg_tabela.getSelectedRow(), 1).toString();
            String nmrtelefone = this.tb_tabelaamg_tabela.getValueAt(this.tb_tabelaamg_tabela.getSelectedRow(), 2).toString();

            this.tf_tabelaamg_nome.setText(nome);
            this.tf_tabelaamg_tel.setText(nmrtelefone);
        }
    }//GEN-LAST:event_tb_tabelaamg_tabelaMouseClicked

    private void bt_tabelaamg_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tabelaamg_deletarActionPerformed
        try{
        
            int ID = 0;
            if (this.tb_tabelaamg_tabela.getSelectedRow() == -1){
                throw new Mensagens("Primeiro selecione um amigo para deletar.");
            } else {
                ID = Integer.parseInt(this.tb_tabelaamg_tabela.getValueAt(this.tb_tabelaamg_tabela.getSelectedRow(),0).toString());
            } 
            
            int resposta_usuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja deletar este amigo?");
            
            if (resposta_usuario == 0) {
            
                if (this.objeto.DeleteAmigoBD(ID)){
                
                    this.tf_tabelaamg_nome.setText("");
                    this.tf_tabelaamg_tel.setText("");
                    JOptionPane.showMessageDialog(null,"Amigo deletado com sucesso!");
                }
            }
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null,erro.getMessage());
        } finally {
            carregaTabela();
        }
    }//GEN-LAST:event_bt_tabelaamg_deletarActionPerformed

    /**
         * @param args the command line arguments
         */
    @SuppressWarnings("unchecked")
    public void carregaTabela(){
    
        DefaultTableModel modelo = (DefaultTableModel) this.tb_tabelaamg_tabela.getModel();
        modelo.setNumRows(0);
        
        ArrayList<Amigo> minhalista = new ArrayList<>();
        minhalista = objeto.getMinhaLista();
        
        for (Amigo a : minhalista) {
            modelo.addRow(new Object[] {
                a.getID(),
                a.getNome(),
                a.getNmrtelefone(),
            });
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaAmigos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_tabelaamg_deletar;
    private javax.swing.JButton bt_tabelaamg_editar;
    private javax.swing.JButton bt_tabelaamg_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_tabelaamg_tabela;
    private javax.swing.JTextField tf_tabelaamg_nome;
    private javax.swing.JTextField tf_tabelaamg_tel;
    // End of variables declaration//GEN-END:variables
}
