package View.Ferramentas;

import Model.Ferramenta;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class CadastrarFerramenta extends javax.swing.JFrame {
    
    private Ferramenta objeto;

    public CadastrarFerramenta() {
        initComponents();
        this.objeto = new Ferramenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_cadasferr_modelo = new javax.swing.JTextField();
        tf_cadasferr_marca = new javax.swing.JTextField();
        tf_cadasferr_preco = new javax.swing.JTextField();
        bt_cadasferr_cadastra = new javax.swing.JButton();
        bt_cadasferr_cancela = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de ferramenta");

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel1.setText("Marca:");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel2.setText("Modelo:");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel3.setText("Preço:");

        tf_cadasferr_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cadasferr_modeloActionPerformed(evt);
            }
        });

        tf_cadasferr_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cadasferr_marcaActionPerformed(evt);
            }
        });

        tf_cadasferr_preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cadasferr_precoActionPerformed(evt);
            }
        });

        bt_cadasferr_cadastra.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        bt_cadasferr_cadastra.setText("Cadastrar");
        bt_cadasferr_cadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadasferr_cadastraActionPerformed(evt);
            }
        });

        bt_cadasferr_cancela.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        bt_cadasferr_cancela.setText("Cancelar");
        bt_cadasferr_cancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadasferr_cancelaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 2, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nova ferramenta");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_cadasferr_cadastra)
                        .addGap(184, 184, 184)
                        .addComponent(bt_cadasferr_cancela))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_cadasferr_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_cadasferr_marca))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_cadasferr_modelo))
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_cadasferr_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_cadasferr_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_cadasferr_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cadasferr_cadastra)
                    .addComponent(bt_cadasferr_cancela))
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cadasferr_cancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadasferr_cancelaActionPerformed
        this.setVisible(false);
        GerenciarFerramentas objeto = new GerenciarFerramentas();
        objeto.setVisible(true);
    }//GEN-LAST:event_bt_cadasferr_cancelaActionPerformed

    private void tf_cadasferr_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cadasferr_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cadasferr_modeloActionPerformed

    private void tf_cadasferr_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cadasferr_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cadasferr_marcaActionPerformed

    private void tf_cadasferr_precoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cadasferr_precoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cadasferr_precoActionPerformed

    private void bt_cadasferr_cadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadasferr_cadastraActionPerformed
        try {
            String modelo = "";
            String marca = "";
            double preco = 0;
            
            if (this.tf_cadasferr_marca.getText().length() <= 0){
                throw new Mensagens ("O campo 'marca' deve ser preenchido.");
            } else {
                marca = this.tf_cadasferr_marca.getText();
            }
            
            if (this.tf_cadasferr_modelo.getText().length() <= 0){
                throw new Mensagens ("O campo 'modelo' deve ser preenchido.");
            } else {
                modelo = this.tf_cadasferr_modelo.getText();
            }
            
            if (this.tf_cadasferr_preco.getText().length() <= 0){
                throw new Mensagens("O campo 'preço' deve ser preenchido.");
            } else {
                preco = Double.parseDouble(this.tf_cadasferr_preco.getText());
            }
            
            if (this.objeto.InsertFerramentaBD(modelo, marca, preco)){
                JOptionPane.showMessageDialog(rootPane, "Ferramenta cadastrada com sucesso!");
                
                this.tf_cadasferr_modelo.setText("");
                this.tf_cadasferr_marca.setText("");
                this.tf_cadasferr_preco.setText("");
            }
            
            
        } catch (Mensagens erro){
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (SQLException ex) {
            Logger.getLogger(CadastrarFerramenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_cadasferr_cadastraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFerramenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cadasferr_cadastra;
    private javax.swing.JButton bt_cadasferr_cancela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tf_cadasferr_marca;
    private javax.swing.JTextField tf_cadasferr_modelo;
    private javax.swing.JTextField tf_cadasferr_preco;
    // End of variables declaration//GEN-END:variables
}
