/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Ferramentas;

import View.Telaprincipal;

/**
 *
 * @author lucas
 */
public class GerenciarFerramentas extends javax.swing.JFrame {

    /**
     * Creates new form GerenciarFerramentas
     */
    public GerenciarFerramentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_gerferr_cadastroferramenta = new javax.swing.JButton();
        bt_gerferr_tabelaferramenta = new javax.swing.JButton();
        bt_gerferr_sair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciar Ferramentas");
        setMaximumSize(new java.awt.Dimension(450, 380));
        setPreferredSize(new java.awt.Dimension(450, 380));

        bt_gerferr_cadastroferramenta.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        bt_gerferr_cadastroferramenta.setText("Cadastrar ferramenta");
        bt_gerferr_cadastroferramenta.setHideActionText(true);
        bt_gerferr_cadastroferramenta.setMaximumSize(new java.awt.Dimension(148, 23));
        bt_gerferr_cadastroferramenta.setMinimumSize(new java.awt.Dimension(148, 23));
        bt_gerferr_cadastroferramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gerferr_cadastroferramentaActionPerformed(evt);
            }
        });

        bt_gerferr_tabelaferramenta.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        bt_gerferr_tabelaferramenta.setText("Tabela de ferramentas");
        bt_gerferr_tabelaferramenta.setHideActionText(true);
        bt_gerferr_tabelaferramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gerferr_tabelaferramentaActionPerformed(evt);
            }
        });

        bt_gerferr_sair.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        bt_gerferr_sair.setText("Voltar");
        bt_gerferr_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gerferr_sairActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 2, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ferramentas");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_gerferr_cadastroferramenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_gerferr_tabelaferramenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_gerferr_sair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(bt_gerferr_cadastroferramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_gerferr_tabelaferramenta)
                .addGap(18, 18, 18)
                .addComponent(bt_gerferr_sair)
                .addGap(100, 100, 100))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_gerferr_tabelaferramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gerferr_tabelaferramentaActionPerformed
        TabelaFerramentas objeto = new TabelaFerramentas();
        objeto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_gerferr_tabelaferramentaActionPerformed

    private void bt_gerferr_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gerferr_sairActionPerformed
        this.setVisible(false);
        Telaprincipal objeto = new Telaprincipal();
        objeto.setVisible(true);
    }//GEN-LAST:event_bt_gerferr_sairActionPerformed

    private void bt_gerferr_cadastroferramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gerferr_cadastroferramentaActionPerformed
        CadastrarFerramenta objeto = new CadastrarFerramenta();
        objeto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_gerferr_cadastroferramentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarFerramentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_gerferr_cadastroferramenta;
    private javax.swing.JButton bt_gerferr_sair;
    private javax.swing.JButton bt_gerferr_tabelaferramenta;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
