package View.Ferramentas;

import Model.Ferramenta;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TabelaFerramentas extends javax.swing.JFrame {
    
    private Ferramenta objeto;

    public TabelaFerramentas() {
        initComponents();
        this.objeto = new Ferramenta();
        this.carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_tabelaferr_tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_tabelaferr_modelo = new javax.swing.JTextField();
        tf_tabelaferr_marca = new javax.swing.JTextField();
        tf_tabelaferr_preco = new javax.swing.JTextField();
        bt_tabelaferr_editar = new javax.swing.JButton();
        bt_tabelaferr_deletar = new javax.swing.JButton();
        bt_tabelaferr_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabela de ferramentas");

        tb_tabelaferr_tabela.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        tb_tabelaferr_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Modelo", "Marca", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_tabelaferr_tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_tabelaferr_tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_tabelaferr_tabela);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel1.setText("Modelo:");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel2.setText("Marca:");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel3.setText("Preço:");

        tf_tabelaferr_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tabelaferr_modeloActionPerformed(evt);
            }
        });

        tf_tabelaferr_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tabelaferr_marcaActionPerformed(evt);
            }
        });

        bt_tabelaferr_editar.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        bt_tabelaferr_editar.setText("Editar");
        bt_tabelaferr_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tabelaferr_editarActionPerformed(evt);
            }
        });

        bt_tabelaferr_deletar.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        bt_tabelaferr_deletar.setText("Deletar");
        bt_tabelaferr_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tabelaferr_deletarActionPerformed(evt);
            }
        });

        bt_tabelaferr_sair.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        bt_tabelaferr_sair.setText("Voltar");
        bt_tabelaferr_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tabelaferr_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_tabelaferr_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt_tabelaferr_editar)
                                .addGap(86, 86, 86)
                                .addComponent(bt_tabelaferr_deletar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_tabelaferr_sair))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_tabelaferr_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_tabelaferr_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_tabelaferr_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_tabelaferr_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_tabelaferr_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_tabelaferr_editar)
                    .addComponent(bt_tabelaferr_deletar)
                    .addComponent(bt_tabelaferr_sair))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_tabelaferr_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tabelaferr_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tabelaferr_modeloActionPerformed

    private void bt_tabelaferr_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tabelaferr_sairActionPerformed
        this.setVisible(false);
        GerenciarFerramentas objeto = new GerenciarFerramentas();
        objeto.setVisible(true);
    }//GEN-LAST:event_bt_tabelaferr_sairActionPerformed

    private void tf_tabelaferr_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tabelaferr_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tabelaferr_marcaActionPerformed

    private void bt_tabelaferr_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tabelaferr_editarActionPerformed
        
        try {

            int id = 0;
            String modelo = "";
            String marca = "";
            double preco = 0;

            if (this.tf_tabelaferr_modelo.getText().length() <= 0) {
                throw new Mensagens("O campo 'modelo' deve ser preenchido.");
            } else {
                modelo = this.tf_tabelaferr_modelo.getText();
            }

            if (this.tf_tabelaferr_marca.getText().length() <= 0) {
                throw new Mensagens("O campo 'marca' deve ser preenchido.");
            } else {
                marca = this.tf_tabelaferr_marca.getText();
            }
            
            if (this.tf_tabelaferr_preco.getText().length() <= 0){
                throw new Mensagens("O campo 'preço' deve ser preenchido.");
            } else {
                preco = Double.parseDouble(this.tf_tabelaferr_preco.getText());
            }

            if (this.tb_tabelaferr_tabela.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro selecione uma ferramenta para editar.");
            } else {
                id = Integer.parseInt(this.tb_tabelaferr_tabela.getValueAt(this.tb_tabelaferr_tabela.getSelectedRow(), 0).toString());
            }

            if (this.objeto.UpdateFerramentaBD(modelo, marca, preco, id)) {

                this.tf_tabelaferr_modelo.setText("");
                this.tf_tabelaferr_marca.setText("");
                this.tf_tabelaferr_preco.setText("");
                JOptionPane.showMessageDialog(rootPane, "Ferramenta editada com sucesso");

            }
             System.out.println(this.objeto.getMinhaLista().toString());
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            carregaTabela();
        }
    }//GEN-LAST:event_bt_tabelaferr_editarActionPerformed

    private void tb_tabelaferr_tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_tabelaferr_tabelaMouseClicked
        
        if (this.tb_tabelaferr_tabela.getSelectedRow() != -1) {

            String modelo = this.tb_tabelaferr_tabela.getValueAt(this.tb_tabelaferr_tabela.getSelectedRow(), 1).toString();
            String marca = this.tb_tabelaferr_tabela.getValueAt(this.tb_tabelaferr_tabela.getSelectedRow(), 2).toString();
            String preco = this.tb_tabelaferr_tabela.getValueAt(this.tb_tabelaferr_tabela.getSelectedRow(), 3).toString();

            this.tf_tabelaferr_modelo.setText(modelo);
            this.tf_tabelaferr_marca.setText(marca);
            this.tf_tabelaferr_preco.setText(preco);
        }
    }//GEN-LAST:event_tb_tabelaferr_tabelaMouseClicked

    private void bt_tabelaferr_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tabelaferr_deletarActionPerformed
        
        try{
        
            int ID = 0;
            if (this.tb_tabelaferr_tabela.getSelectedRow() == -1){
                throw new Mensagens("Primeiro selecione uma ferramenta para deletar");
            } else {
                ID = Integer.parseInt(this.tb_tabelaferr_tabela.getValueAt(this.tb_tabelaferr_tabela.getSelectedRow(),0).toString());
            } 
            
            int resposta_usuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja deletar esta ferramenta?");
            
            if (resposta_usuario == 0) {
            
                if (this.objeto.DeleteFerramentaBD(ID)){
                
                    this.tf_tabelaferr_modelo.setText("");
                    this.tf_tabelaferr_marca.setText("");
                    this.tf_tabelaferr_preco.setText("");
                    JOptionPane.showMessageDialog(null,"Ferramenta deletada com sucesso!");
                }
            }
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null,erro.getMessage());
        } finally {
            carregaTabela();
        }
    }//GEN-LAST:event_bt_tabelaferr_deletarActionPerformed

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("unchecked")
    public void carregaTabela(){
    
        DefaultTableModel modelo = (DefaultTableModel) this.tb_tabelaferr_tabela.getModel();
        modelo.setNumRows(0);
        
        ArrayList<Ferramenta> minhalista = new ArrayList<>();
        minhalista = objeto.getMinhaLista();
        
        for (Ferramenta a : minhalista){
            modelo.addRow(new Object[]{
            a.getID(),
            a.getModelo(),
            a.getMarca(),
            a.getPreco()});
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaFerramentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_tabelaferr_deletar;
    private javax.swing.JButton bt_tabelaferr_editar;
    private javax.swing.JButton bt_tabelaferr_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_tabelaferr_tabela;
    private javax.swing.JTextField tf_tabelaferr_marca;
    private javax.swing.JTextField tf_tabelaferr_modelo;
    private javax.swing.JTextField tf_tabelaferr_preco;
    // End of variables declaration//GEN-END:variables
}
